spring.application.name=webid
spring.data.mongodb.uri=mongodb+srv://webid:webid123@cluster0.lnjowsz.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=webid
server.port=8081
logging.level.org.springframework.web=DEBUG
spring.data.mongodb.auto-index-creation=true
